### ISSUE TITLE
Yarn error: workspaces are only allowed in private packages

### ISSUE THREAD

**Issue by jasikpark** [gabrielcsapo/miette#4]
When trying to setup the git repo I got this output

```sh
gitpod /workspace/miette $ yarn
yarn install v1.22.17
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
error Workspaces can only be enabled in private projects.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This is because you don't have `"private": "true"` on the top-level package -- in yarn you have a top level private package + multiple lower level packages that can be published.

Maybe it could be reworked to be:

```sh
package.json
miette
| package.json
website
| package.json
```

**Comment by gabrielcsapo** [comment]
Looking into this now, will checkout how to fix it.

**Comment by jasikpark** [comment]
This tool looks really cool btw, I'm excited to see it be something great! https://github.com/snowpackjs/astro is a good example of the setup of a solid workspace IMO

**Comment by gabrielcsapo** [comment]
Thank you! @zkat started the trend and I just jumped on the train.

I have a PR open and am using lerna like astro is! I am going to make sure CI builds and docs deploy correctly before I merge in.

**Comment by gabrielcsapo** [comment]
Verified the fix and we are good to go!
